README.md

@emiliom just to get is started on something.

add draft curriculum and folders

---

environment.yml

We can add the extras later in another PR, just want to check if this works.

use r-tidyverse instead of listing a bunch of packages

---

.appveyor.yml
.travis.yml
environment.yml

Pinging @btupper and @SeascapeScience.

More r pkgs

---

environment.yml

I think this updates the list of R packages to include what we need and to eliminate some redundancies.

modify environment.yml to include remotes, sf and rastervis

---

README.md
environment.yml

Pinging @mpachiad and @btupper so you can take the install instructions for a test-drive.

Install instructions

---

08-R-tutorials/08-OBIS-access.ipynb
08-R-tutorials/08-extracting_rasters.ipynb
08-R-tutorials/08-intro_to_OBPG.ipynb
environment.yml

A.  I discovered that we need add two more R packages - they are in the environment.yml. I hope I have them all now.
B. I found https://github.com/vatlab/sos-rmarkdown for converting Rmarkdown to Jupyter notebook - examples included in the new 08-R-tutorials directory.  More to come, but thought we should give these a shake early.

Jupyter notebooks for R and two missing R packages

---

environment.yml

In the future we should fetch this file from here directly or vice-versa. But we should not maintain both!

sync image and tutorial envs

---

environment.yml

In response to #6 . CoTeDe was just merged into master.

Adding Gui's packages from conda-forge

---

08-R-tutorials/deriving_rasters.Rmd
08-R-tutorials/extracting_rasters.Rmd
08-R-tutorials/intro_to_OBPG.Rmd
08-R-tutorials/plotting_rasters.Rmd

We're adding in some Markdown versions of the python notebooks to make an end-run around a leaflet issue we are having.  Plus we think it might be useful to demonstrate a use case for RStudio/RMarkdown.

add Rmarkdown tutorial versions

---

10-satellite-data-access/era5_make_zarr.ipynb
10-satellite-data-access/goes-cmp-netcdf-zarr.ipynb
10-satellite-data-access/netcdf_to_zarr_GEO_data.ipynb

some updates to the other tutorials in sat-data-access

Cgentemann patch 1

---

r-keras-test/2.1-a-first-look-at-a-neural-network.Rmd

Let me know if it doesn't work.

Added test for R keras configuration

---

Data-Access/DataAccess.ipynb

This is not the variable you are looking for.

remove runaway code cell

---

.gitignore
03-Thu/00-machine-learning/00-unsupervised-PCA.ipynb
03-Thu/00-machine-learning/01-unsupervised-kmeans.ipynb
03-Thu/00-machine-learning/02-supervised-knn.ipynb
03-Thu/00-machine-learning/pellets-visual-classes-rgb.csv

Machine learning Tuesday

---

README.md

Syncing with latest schedule from the webpage.

sync schedule

---

00-Mon/xarray-in-45-min.ipynb

Closes #73 
Copied from [here](https://tutorial.xarray.dev/overview/xarray-in-45-min.html); could use that link for an easy review

Add Xarray tutorial

---

01-Tue/00-data-access/00-data-access.ipynb
optional/managing-conda-envs/README.md

We should probably put those in the webpage but I don't think it is worth doing that now.

add conda-env optional tutorial

---

00-Mon/conda-env-tutorial.txt

Add conda env tutorial

---

00-Mon/reproducable-research

Same as #110 but in the right branch.

add repro tutorial

---

00-Mon/README.md

- Add Joseph's presentation pdf to the OHW23 00-Monday folder
- Add a README file to 00-Monday folder with links to today's tutorials. We can add youtube links there, when ready.

Updates to OHW23 Monday tutorials

---

01-Tue/README.md

Currently only has the IMOS data access tutorial. Already added YouTube link

Create README.md for Tuesday tutorials / data access

---

00-Mon/README.md
01-Tue/README.md
02-Wed/README.md
03-Thr/README.md
04-Fri/README.md

Adding a base structure for the tutorial folders for each day.

adding base structure for tutorial folders

---

us/00-Mon/packages-and-jupyter/pixi-package-mgmt.ipynb
us/00-Mon/packages-and-jupyter/simple_kml_example.ipynb

Pull request to merge in tutorial notebooks for ohw24, with branch correctly off of OHW24

Tutorial notebooks for pixi demonstration, added off OHW24 branch

---

us/01-Tue/data-access-in-python/00-data-access.ipynb

One of the datasets for my demo tomorrow has dropped off the internet. It's the last demo of the notebook though, so not disastrous if it's not merged on time.
Nice talking point to illustrate bitrot!

Replace missing remote dataset

---

us/03-Thr/RApplication/RApplicationTutorial.R

Adding R Application tutorial materials

adding tutorial materials
